name: Spring boot deploy

on:
  push:
    branches:
      - 'Dev/BE'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Grant execute permission for gradlew
      working-directory: ./be/cocktail
      run: chmod +x gradlew
    
    - name: Build with Gradle
      working-directory: ./be/cocktail
      run: ./gradlew clean build

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Docker build and push
      uses: docker/build-push-action@v4
      with:
        context: ./be/cocktail
        file: ./be/cocktail/Dockerfile
        push: true
        tags: yusunro/seb43_main_011:latest

  run-compose:
    runs-on: self-hosted
    needs: build-and-deploy
    steps:
      - name: Docker run
        run: |
          cd /home/ubuntu
          sudo docker-compose down
          sudo docker-compose pull
          sudo docker-compose up -d
